include $(CLEAR_VARS)

LOCAL_ADDITIONAL_INSTALL_DEPENDENCIES :=
LOCAL_INSTALLED_REQUIRED_XPCOM_IDL_HEADERS :=
LOCAL_INSTALLED_XPCOM_IDLS :=
LOCAL_INSTALLED_XPCOM_IDL_HEADERS :=
LOCAL_JS_NOTICE :=
LOCAL_JS_SRC_FILES :=
LOCAL_JS_LINTONLY_FILES :=
LOCAL_JSLINT_FATAL :=
LOCAL_XPCOM_IDLS :=
LOCAL_XPCOM_INSTALL_DIR :=
LOCAL_XPCOM_MODULE_OBJDIR :=
LOCAL_XPCOM_SHARED_LIBRARIES :=
LOCAL_XPCOM_STATIC_LIBRARIES :=
LOCAL_XPIDL_FLAGS :=
LOCAL_XPIDL_OUT :=
